---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Add Nginx Configuration File
  template:
    src: magento.j2
    dest: /etc/nginx/sites-available/magento
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
  - Reload Nginx Configuration

- name: Create Symbolic Link
  file:
    src: /etc/nginx/sites-available/magento
    dest: /etc/nginx/sites-enabled/magento
    owner: root
    group: root
    state: link
  notify:
  - Reload Nginx Configuration

- name: Start Nginx Service
  service:
    name: nginx
    state: started
    enabled: true
